import type { Metadata } from "next";
import { Inter, Poppins, Raleway } from "next/font/google";
import "./globals.css";
import { Providers } from "@/redux/providers";
import Navbar from "@/components/Navbar";
import { ProvidersAuth } from "./Providers";

const inter = Raleway({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

export const metadata: Metadata = {
  title: "Wallet App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-[#0C395A] bg-cover bg-fixed bg-[30%] bg-[url('/images/degra-blue.jpg')] min-h-screen Xpr-10">
          <Providers>
            <ProvidersAuth>
              <Navbar />
              {children}
            </ProvidersAuth>
          </Providers>
        </div>
      </body>
    </html>
  );
}
